
font_family Iosevka Nerd Font
allow_remote_control yes
enable_scrollback_in_multiplexers yes
font_size 13.0
disable_ligatures never

include ~/.cache/wal/colors-kitty.conf
window_padding_width 10
enable_background_opacity yes
url_color #e8eaed


confirm_os_window_close 0
